version: "3.3"

services:
  db:
    image: postgres:13
    volumes:
      - ./data/db_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
